### ISSUE TITLE
bisheng-rt 0.0.3  docker 不支持InternLM

### ISSUE THREAD

**Issue by rainySummers** [dataelement/bisheng#102]
dataelement/bisheng-rt:0.0.3 docker hub的版本代码与github代码版本不一致
docker中：
![image](https://github.com/dataelement/bisheng/assets/26564422/8e76568b-c1e0-4985-9496-d973fac5667a)
github上：
![image](https://github.com/dataelement/bisheng/assets/26564422/9a9adc99-875f-444a-b045-69a940075e4b)

**Comment by yaojin3616** [comment]
最近新发布了  dataelement/bisheng-rt:0.0.3.alpha1 版本，支持了InternLMChat 和 CodeGeex

**Comment by yaojin3616** [comment]
https://dataelem.feishu.cn/wiki/HpIewJMBIiIPmMkg6T1czihrnWZ
可以参考这个文档看下
