### ISSUE TITLE
2023年10.25新版本配置文档读取问题

### ISSUE THREAD

**Issue by fengfeizi** [dataelement/bisheng#107]
新版本更新后配置启动后台配置文档出现读取配置文档会抽取后面全部内容的问题，导致插入mysql报 "Data too long for column ivalue' 异常
![151b8c0f1edec28548b60064f9c6755](https://github.com/dataelement/bisheng/assets/147676590/c50c5571-c67f-41f2-b248-e715d3e70f77)

**Comment by yaojin3616** [comment]
收到，感谢反馈。 在0.1.9 中加大了配置字段
当前辛苦手动修改mysql都字段长度。 
alter table config modify value varchar(4096) comment '配置值';
