### ISSUE TITLE
知识库embbeding支持

### ISSUE THREAD

**Issue by zengqi0730** [dataelement/bisheng#110]
创建知识库时，代码里只能选择openai的：
```
def decide_embeddings(model: str) -> Embeddings:
    model_list = settings.get_knowledge().get('embeddings')
    if model == 'text-embedding-ada-002':
        return OpenAIEmbeddings(**model_list.get(model))
    else:
        return HostEmbeddings(**model_list.get(model))

```
我想换其他的embbeding，是需要自行实现吗？

**Comment by yaojin3616** [comment]
https://dataelem.feishu.cn/wiki/BSCcwKd4Yiot3IkOEC8cxGW7nPc
参考这个文档，当前支持openai和本地模型
![image](https://github.com/dataelement/bisheng/assets/3382757/2e0c020b-145f-41a7-a47e-a83f44e2cd09)
其他需要自己实现
