### ISSUE TITLE
Feature: Adding contributors section to the README.md file

### ISSUE THREAD

**Issue by Kalyanimhala** [dataelement/bisheng#112]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/dataelement/bisheng/assets/147402107/3dfc97a7-423f-4801-8c9e-0c96363571c1)

**Comment by Kalyanimhala** [comment]
@hrfng Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by yaojin3616** [comment]
very appreciate for your advise,  we'll release our english language mode in next version~
