### ISSUE TITLE
hi 这里单文档问答出现了一些问题

### ISSUE THREAD

**Issue by dingli06** [dataelement/bisheng#129]
使用了默认配置，没有使用任何高级配置的内容
![7582f5c417bc27c6f57656f0d14190d](https://github.com/dataelement/bisheng/assets/63959467/b50bfa3f-aea1-4948-98c8-c15ae4c9f361)

**Comment by yaojin3616** [comment]
这个错误是调用模型错误，一般有：
1. token 超过模型长度
2. 模型credit 过期

**Comment by dingli06** [comment]
> 这个错误是调用模型错误，一般有：
> 
> 1. token 超过模型长度
> 2. 模型credit 过期

难道是文档直接喂给模型吗,没有做片段召回？

**Comment by yaojin3616** [comment]
> > 这个错误是调用模型错误，一般有：
> > 
> > 1. token 超过模型长度
> > 2. 模型credit 过期
> 
> 难道是文档直接喂给模型吗,没有做片段召回？

有的，这个和技能的设置相关。

**Comment by yaojin3616** [comment]
已经将错误信息正常展示
