### ISSUE TITLE
退出时，不能删除cookie

### ISSUE THREAD

**Issue by xiuhuai** [dataelement/bisheng#149]
登录用户退出时，不能删除cookie，因为cookie在创建时，被设置了HttpOnly属性。可能需要使用服务器端的代码来完成。例如在服务器端发送一个特殊的响应头，告诉浏览器删除特定的cookie。然后浏览器会删除这个cookie。
版本：0.1.9.5
代码位置：src\layout\MainLayout.tsx的23-32行
代码片段：

```
function clearAllCookies() {
        var cookies = document.cookie.split(";");

        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i];
            var eqPos = cookie.indexOf("=");
            var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
            document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
        }
    }
```

附图：
![1](https://github.com/dataelement/bisheng/assets/25577285/a3da8cc0-50a7-425d-942f-7d159ba1b6a9)

**Comment by dolphin0618** [comment]
已知问题，下个版本更新
