### ISSUE TITLE
embedding模型与向量搜索相关的一些问题

### ISSUE THREAD

**Issue by keenouter** [dataelement/bisheng#167]
目前有以下几个问题

1、我们目前有一些自定义的embedding模型，但是由于接口定义不同没法直接接入，这一块是否会考虑支持开放自定义接口

2、vector 知否支持其他应用已存在的知识库，非bisheng应用内建立的知识库

3、新建技能保存以后无法直接点击打开，需要刷新页面以后才会出现打开按钮

**Comment by yaojin3616** [comment]
1. 自定义模型目前设计的是支持RT私有化部署的模型，后续开放接口我看怎么排期
2. vector 目前也是支持es和milvus，其他的需要再考虑
3. 新版本已经修复
