### ISSUE TITLE
知识库上传非常小的txt文件，提示  KeyError: 'page'    

### ISSUE THREAD

**Issue by xiuhuai** [dataelement/bisheng#184]
请问在知识库里上传txt文件时，提示KeyError: 'page'    ，如何解决，谢谢
模型为：multilingual-e5-large
后台图示：![0](https://github.com/dataelement/bisheng/assets/25577285/d7e1ad47-ad84-4b48-b85c-e33768423e5d)
错误代码为：
`docker-backend-1  | /app/bisheng/api/v1/knowledge.py:317: SAWarning: DELETE statement on table 'knowledgefile' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
docker-backend-1  |   session.commit()
docker-backend-1  | INFO:     172.18.0.4:35386 - "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 49 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35394 - "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 49 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35410 - "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 49 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35426 - "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 286 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | [15:59:46] INFO     [15:59:46] - INFO - act=delete_vector       knowledge.py:304
docker-backend-1  |                     file_id=37 res=(insert count: 0, delete                     
docker-backend-1  |                     count: 0, upsert count: 0, timestamp:                       
docker-backend-1  |                     446114558432247810, success count: 0, err                   
docker-backend-1  |                     count: 0)                                                   
docker-backend-1  |            DEBUG    [15:59:46] - DEBUG - Starting new HTTP connectionpool.py:246
docker-backend-1  |                     connection (1): 192.168.1.14:9200                           
docker-backend-1  |            DEBUG    [15:59:46] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://192.168.1.14:9200 "GET                               
docker-backend-1  |                     /col_1701791122_ab9c9ef8 HTTP/1.1" 200                      
docker-backend-1  |                     None                                                        
docker-backend-1  |            INFO     [15:59:46] - INFO - GET                    _transport.py:335
docker-backend-1  |                     http://192.168.1.14:9200/col_1701791122_ab                  
docker-backend-1  |                     9c9ef8 [status:200 duration:0.006s]                         
docker-backend-1  |            DEBUG    [15:59:46] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://192.168.1.14:9200 "POST                              
docker-backend-1  |                     /col_1701791122_ab9c9ef8/_refresh                           
docker-backend-1  |                     HTTP/1.1" 200 49                                            
docker-backend-1  |            INFO     [15:59:46] - INFO - POST                   _transport.py:335
docker-backend-1  |                     http://192.168.1.14:9200/col_1701791122_ab                  
docker-backend-1  |                     9c9ef8/_refresh [status:200                                 
docker-backend-1  |                     duration:0.004s]                                            
docker-backend-1  |            DEBUG    [15:59:46] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://192.168.1.14:9200 "POST                              
docker-backend-1  |                     /col_1701791122_ab9c9ef8/_delete_by_qu                      
docker-backend-1  |                     ery HTTP/1.1" 200 215                                       
docker-backend-1  |            INFO     [15:59:46] - INFO - POST                   _transport.py:335
docker-backend-1  |                     http://192.168.1.14:9200/col_1701791122_ab                  
docker-backend-1  |                     9c9ef8/_delete_by_query [status:200                         
docker-backend-1  |                     duration:0.006s]                                            
docker-backend-1  |            INFO     [15:59:46] - INFO - act=delete_es           knowledge.py:314
docker-backend-1  |                     file_id=37 res={'took': 2, 'timed_out':                     
docker-backend-1  |                     False, 'total': 0, 'deleted': 0, 'batches':                 
docker-backend-1  |                     0, 'version_conflicts': 0, 'noops': 0,                      
docker-backend-1  |                     'retries': {'bulk': 0, 'search': 0},                        
docker-backend-1  |                     'throttled_millis': 0,                                      
docker-backend-1  |                     'requests_per_second': -1.0,                                
docker-backend-1  |                     'throttled_until_millis': 0, 'failures':                    
docker-backend-1  |                     []}                                                         
docker-backend-1  | INFO:     172.18.0.4:35412 - "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "DELETE /api/v1/knowledge/file/37 HTTP/1.1" 200 49 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35432 - "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 286 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35438 - "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 286 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | INFO:     172.18.0.4:35448 - "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 OK
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:46 +0000] "GET /api/v1/knowledge/file_list/4?page_size=20&page_num=1 HTTP/1.1" 200 286 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | [15:59:56] DEBUG    [15:59:56] - DEBUG - Calling on_part_begin  multipart.py:586
docker-backend-1  |                     with no data                                                
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling                multipart.py:583
docker-backend-1  |                     on_header_field with data[42:61]                            
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling                multipart.py:583
docker-backend-1  |                     on_header_value with data[63:104]                           
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling on_header_end  multipart.py:586
docker-backend-1  |                     with no data                                                
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling                multipart.py:583
docker-backend-1  |                     on_header_field with data[106:118]                          
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling                multipart.py:583
docker-backend-1  |                     on_header_value with data[120:130]                          
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling on_header_end  multipart.py:586
docker-backend-1  |                     with no data                                                
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling                multipart.py:586
docker-backend-1  |                     on_headers_finished with no data                            
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling on_part_data   multipart.py:583
docker-backend-1  |                     with data[134:1073]                                         
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling on_part_end    multipart.py:586
docker-backend-1  |                     with no data                                                
docker-backend-1  |            DEBUG    [15:59:56] - DEBUG - Calling on_end with no multipart.py:586
docker-backend-1  |                     data                                                        
docker-backend-1  | INFO:     172.18.0.4:40154 - "POST /api/v1/knowledge/upload HTTP/1.1" 201 Created
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:56 +0000] "POST /api/v1/knowledge/upload HTTP/1.1" 201 130 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  | [15:59:57] INFO     [15:59:57] - INFO - fileName=qa.txt         knowledge.py:132
docker-backend-1  |                     col=col_1701791122_ab9c9ef8                                 
docker-backend-1  | INFO:     172.18.0.4:40158 - "POST /api/v1/knowledge/process HTTP/1.1" 201 Created
docker-nginx-1    | 192.168.1.101 - - [05/Dec/2023:15:59:57 +0000] "POST /api/v1/knowledge/process HTTP/1.1" 201 32 "http://192.168.1.14:3001/filelib/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG - Using previous            milvus.py:206
docker-backend-1  |                     connection: 729e04139ed94c7eaeaa3c061c316285                
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG - Nothing to insert,        milvus.py:423
docker-backend-1  |                     skipping.                                                   
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG - Starting new HTTP connectionpool.py:246
docker-backend-1  |                     connection (1): 192.168.1.14:9200                           
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://192.168.1.14:9200 "GET                               
docker-backend-1  |                     /col_1701791122_ab9c9ef8 HTTP/1.1" 200                      
docker-backend-1  |                     None                                                        
docker-backend-1  |            INFO     [15:59:57] - INFO - GET                    _transport.py:335
docker-backend-1  |                     http://192.168.1.14:9200/col_1701791122_ab                  
docker-backend-1  |                     9c9ef8 [status:200 duration:0.006s]                         
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://192.168.1.14:9200 "POST                              
docker-backend-1  |                     /col_1701791122_ab9c9ef8/_refresh                           
docker-backend-1  |                     HTTP/1.1" 200 49                                            
docker-backend-1  |            INFO     [15:59:57] - INFO - POST                   _transport.py:335
docker-backend-1  |                     http://192.168.1.14:9200/col_1701791122_ab                  
docker-backend-1  |                     9c9ef8/_refresh [status:200                                 
docker-backend-1  |                     duration:0.004s]                                            
docker-backend-1  |            INFO     [15:59:57] - INFO - chunk_split             knowledge.py:375
docker-backend-1  |                     file_name=qa.txt size=1                                     
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG - Starting new HTTP connectionpool.py:246
docker-backend-1  |                     connection (1): 172.17.0.1:9001                             
docker-backend-1  |            DEBUG    [15:59:57] - DEBUG -                   connectionpool.py:474
docker-backend-1  |                     http://172.17.0.1:9001 "POST                                
docker-backend-1  |                     /v2.1/models/multilingual-e5-large/inf                      
docker-backend-1  |                     er HTTP/1.1" 200 20427                                      
docker-backend-1  |            ERROR    [15:59:57] - ERROR - 'page'                 knowledge.py:385
docker-backend-1  |                     Traceback (most recent call last):                          
docker-backend-1  |                       File "/app/bisheng/api/v1/knowledge.py",                  
docker-backend-1  |                     line 377, in addEmbedding                                   
docker-backend-1  |                         vectore_client.add_texts(texts=texts,                   
docker-backend-1  |                     metadatas=metadatas)                                        
docker-backend-1  |                       File                                                      
docker-backend-1  |                     "/usr/local/lib/python3.10/site-packages/la                 
docker-backend-1  |                     ngchain/vectorstores/milvus.py", line 454,                  
docker-backend-1  |                     in add_texts                                                
docker-backend-1  |                         insert_list = [insert_dict[x][i:end]                    
docker-backend-1  |                     for x in self.fields]                                       
docker-backend-1  |                       File                                                      
docker-backend-1  |                     "/usr/local/lib/python3.10/site-packages/la                 
docker-backend-1  |                     ngchain/vectorstores/milvus.py", line 454,                  
docker-backend-1  |                     in <listcomp>                                               
docker-backend-1  |                         insert_list = [insert_dict[x][i:end]                    
docker-backend-1  |                     for x in self.fields]                                       
docker-backend-1  |                     KeyError: 'page'    `

**Comment by nolynn** [comment]
什么问题，我也出现这种情况了；
