### ISSUE TITLE
ws服务失败

### ISSUE THREAD

**Issue by jundaychan** [dataelement/bisheng#190]
自己部署成功了，但是开启不了新的对话，一新建会话，就报错。看了下控制台，提示是 ws 的问题。

环境：宝塔 docker

后测试：不配置 https 就会出现这个问题，配置上了就好了

**Comment by yaojin3616** [comment]
应该和你宝塔nginx配置有关

**Comment by dolphin0618** [comment]
具体错误信息是什么呢，使用http 也应该是没问题的
