### ISSUE TITLE
Azure Chat组件问题

### ISSUE THREAD

**Issue by lazyFrogLOL** [dataelement/bisheng#210]

**Comment by lazyFrogLOL** [comment]
由于bisheng使用的langchain版本是0.2x，所以使用AzureChatOpenAI组件，在api version为2023-05-15之后的版本，会报list out of range问题。

具体可见langchain issue: **https://github.com/langchain-ai/langchain/issues/6462**

短期解决：api version参数填2023-05-15。
长期解决：希望项目方能够适配langchain更新版本。

**Comment by yaojin3616** [comment]
正在更新。本次版本将更新
