### ISSUE TITLE
使用Azure一套模型搭配Milvus上传文件解析后进行问答报错字符集问题分析出错，Error: 'latin-1' codec can't encode characters in position 0-31: ordinal not in range(256)

### ISSUE THREAD

**Issue by Rosejacka** [dataelement/bisheng#231]
报错类似字符集编码问题报错

分析出错，Error: 'latin-1' codec can't encode characters in position 0-31: ordinal not in range(256)

**Comment by yaojin3616** [comment]
latin 这个是mysql的报错，可以看下是不是mysql的字符集不正确

**Comment by yaojin3616** [comment]
看到类似问题，是azure的url 最后需要用 / 结尾
