### ISSUE TITLE
如何接入云服务商的大模型服务

### ISSUE THREAD

**Issue by HO-UN** [dataelement/bisheng#255]
我本来尝试使用阿里云的模型API-key进行调用，都是在技能设置界面，我不知道该怎么搭配才能接入模型，下面是阿里云的提示：
“HTTP接口使用POST方式请求https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation ，获取大模型推理结果。”

**Comment by yaojin3616** [comment]
chatQwen 这个
![image](https://github.com/dataelement/bisheng/assets/3382757/2f1b84ef-798e-4773-9afb-7b31ca222d31)

**Comment by yaojin3616** [comment]
![image](https://github.com/dataelement/bisheng/assets/3382757/9ca76729-f489-4673-a466-0b6cc601e8b8)
