### ISSUE TITLE
现在本地的结果也是流式了，能通过传参去控制流式跟非流式的切换吗

### ISSUE THREAD

**Issue by 1085011735** [dataelement/bisheng#267]

**Comment by 1085011735** [comment]
虽然现在返回的结果中，三条答案第一条是流式，后面两条是非流式

**Comment by yaojin3616** [comment]
在系统设置里，有个配置，可以控制流式
![image](https://github.com/dataelement/bisheng/assets/3382757/459289c1-860a-4889-8099-bcee5851a71f)
