### ISSUE TITLE
bisheng-rt 的 http 服务返回 400

### ISSUE THREAD

**Issue by YTed** [dataelement/bisheng#28]
你好，我部署了 bisheng-rt 后端，访问  http://server_ip:9001/ 返回 HTTP 400，用 telnet 测试 9001 端口是通的，是否访问路径问题？

启动命令：

>  docker run --gpus=all -p 9001:9001 -p 9002:9002 -itd --workdir /opt/bisheng-rt --shm-size=10G --name bisheng-rt -v /home/admin/docker-content/bisheng/models:/opt/bisheng-rt/models/model_repository dataelement/bisheng-rt:0.0.1 ./bin/rtserver f

docker 日志：

> 
> =============================
> == Triton Inference Server ==
> =============================
> 
> NVIDIA Release 22.08 (build <unknown>)
> Triton Server Version 2.25.0
> 
> Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
> 
> Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
> 
> This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> By pulling and using the container, you accept the terms and conditions of this license:
> https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> 
> I0914 08:11:09.141870 1 main.cc:2300] bisheng runtime server v0.0.1 is starting...
> 2023-09-14T08:11:09Z I 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f7970000000' with size 268435456
> 2023-09-14T08:11:09Z I 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
> 2023-09-14T08:11:09Z I 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 1 with size 67108864
> 2023-09-14T08:11:09Z I 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 2 with size 67108864
> 2023-09-14T08:11:09Z I 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 3 with size 67108864
> 2023-09-14T08:11:09Z I 1 server.cc:563]
> +------------------+------+
> | Repository Agent | Path |
> +------------------+------+
> +------------------+------+
> 
> 2023-09-14T08:11:09Z I 1 server.cc:633]
> +-------+---------+--------+
> | Model | Version | Status |
> +-------+---------+--------+
> +-------+---------+--------+
> 
> 2023-09-14T08:11:09Z I 1 metrics.cc:870] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3090
> 2023-09-14T08:11:09Z I 1 metrics.cc:870] Collecting metrics for GPU 1: NVIDIA GeForce RTX 3090
> 2023-09-14T08:11:09Z I 1 metrics.cc:870] Collecting metrics for GPU 2: NVIDIA GeForce RTX 3090
> 2023-09-14T08:11:09Z I 1 metrics.cc:870] Collecting metrics for GPU 3: NVIDIA GeForce RTX 3090
> 2023-09-14T08:11:09Z I 1 metrics.cc:761] Collecting CPU metrics
> 2023-09-14T08:11:09Z I 1 grpc_server.cc:4842] Started GRPCInferenceService at 0.0.0.0:9000
> 2023-09-14T08:11:09Z I 1 http_server.cc:4469] Started HTTPService at 0.0.0.0:9001
> 2023-09-14T08:11:09Z I 1 http_server.cc:193] Started Metrics Service at 0.0.0.0:9002
> 

http response:

> HTTP/1.1 400 Bad Request
> Content-Length: 0
> Content-Type: text/plain

**Comment by yaojin3616** [comment]
看下具体的访问url， 目前通过毕昇模型管理，数据配置的url 缺少 ‘/’ 在下个版本中修复

**Comment by YTed** [comment]
@yaojin3616 服务部署在内网 IP 为 192.168.2.220 的机器上，访问 http://192.168.2.220:9001/ 得到如上结果

**Comment by hrfng** [comment]
@YTed  服务启动是正常的
后续可参考：https://dataelem.feishu.cn/wiki/KAl2wfI9nippfDktNKdclIIMnKf

**Comment by YTed** [comment]
@hrfng 也就是说服务正常启动，路径也没问题？但是出现了 400 错误，能通过什么方法调试吗？
