### ISSUE TITLE
bisheng-mysql startup error   启动报错

### ISSUE THREAD

**Issue by gnlan** [dataelement/bisheng#284]
bisheng-mysql  | 2024-01-21 10:07:55+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
bisheng-mysql  | 2024-01-21 10:07:55+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
bisheng-mysql  | 2024-01-21 10:07:55+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.27-1debian10 started.
bisheng-mysql  | mysqld: Error on realpath() on '/var/lib/mysql-files' (Error 2 - No such file or directory)
bisheng-mysql  | 2024-01-21T02:07:56.282896Z 0 [ERROR] [MY-010095] [Server] Failed to access directory for --secure-file-priv. Please make sure that directory exists and is accessible by MySQL Server. Supplied value : /var/lib/mysql-files
bisheng-mysql  | 2024-01-21T02:07:56.282943Z 0 [ERROR] [MY-010119] [Server] Aborting
bisheng-mysql exited with code 0

**Comment by yaojin3616** [comment]
看着是您的mysql默认data目录和我设置的不一致。 
可以查看下您的docker-compose.yaml 将 mysql/data 目录挂载到 /var/lib/mysql-files

**Comment by yaojin3616** [comment]
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -21,7 +21,7 @@ services:
       - "3306:3306"
     volumes:
       - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/conf/my.cnf:/etc/mysql/my.cnf
-      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/data:/var/lib/mysql
+      - ${DOCKER_VOLUME_DIRECTORY:-.}/mysql/data:/var/lib/mysql-files
