### ISSUE TITLE
bisheng使用的几个问题（官网体验地址+自己部署）

### ISSUE THREAD

**Issue by linqingxu** [dataelement/bisheng#314]
使用的应用为官方技能，模型使用包括GPT3.5 chatglm3 baichuan2 qwen-14B，均出现以下问题
1、非知识库内的问题（检索相似度0但是照样回答），即便是空的数据库；
![捕获](https://github.com/dataelement/bisheng/assets/146169982/aad3a23e-11ca-49d0-8408-6bec3ebed3de)
2、回答一半就停住不继续回答；
3、问了一个问题后，再问其他的问题，模型会将上面的问题结合着一起问答；

另外建议应用问答界面添加清空历史聊天记录的功能

**Comment by wisdomqin** [comment]
感谢反馈
1、即使知识库中没有，模型也有概率会根据自有的知识进行回答，可以在提示词中尝试进一步强调，若还不行大概率是模型遵循指令的能力弱。后续我们有计划推出一个功能，如果知识库中没有找到相关内容就强制返回“没有找到相关内容”（或者返回什么支持配置）
2、这个要具体看一下是否稳定复现
3、以为您用的这个技能配了多轮，解决这种场景：Q1:北京今天的温度是多少？A1：0摄氏度；Q2：那昨天的呢？A2：-5摄氏度
第二个问题会根据历史对话改写成”北京昨天的温度是多少“

4、我们支持删除会话，看是否也满足您的需求。

**Comment by linqingxu** [comment]
> 感谢反馈 1、即使知识库中没有，模型也有概率会根据自有的知识进行回答，可以在提示词中尝试进一步强调，若还不行大概率是模型遵循指令的能力弱。后续我们有计划推出一个功能，如果知识库中没有找到相关内容就强制返回“没有找到相关内容”（或者返回什么支持配置） 2、这个要具体看一下是否稳定复现 3、以为您用的这个技能配了多轮，解决这种场景：Q1:北京今天的温度是多少？A1：0摄氏度；Q2：那昨天的呢？A2：-5摄氏度 第二个问题会根据历史对话改写成”北京昨天的温度是多少“
> 
> 4、我们支持删除会话，看是否也满足您的需求。

关于问题1，添加了强调无参考文本拒绝回答，但依旧会胡编（甚至不是模型自身的内容）；
关于问题3，技能是多轮聊天的知识库问答增强版，有chat_hitstory的情况下是否有什么方案方便用户对下一个问题进行提问，而不是直接将chat_history无差别替换当前问题的主体？还是只能新建一个会话从而开启一个新问题的问答。

**Comment by yaojin3616** [comment]
问题1，可以继续给一个你这边的截图
问题3， 理论上是不会无差别的替换的。 他是根据最新的问题结合历史问题去判断当前应该怎么完善问题。

**Comment by linqingxu** [comment]
模型参数量较少时，遵循prompt的能力不足（7B以下模型，14B的qwen没试过），得找其他方式避免幻觉，例如当参考文本为空，接一个固定回答的组件，不走LLM，一个小意见，大佬们加油，bisheng很棒。

**Comment by wisdomqin** [comment]
> 模型参数量较少时，遵循prompt的能力不足（7B以下模型，14B的qwen没试过），得找其他方式避免幻觉，例如当参考文本为空，接一个固定回答的组件，不走LLM，一个小意见，大佬们加油，bisheng很棒。

嗯嗯，这个功能有在计划中~

**Comment by RusselLeekok** [comment]
<img width="752" height="284" alt="Image" src="https://github.com/user-attachments/assets/179e95c4-46ed-4ac2-9279-b2f0935a4a8f" />

在创建助手后显示助手服务错误请问有解决方法吗
