### ISSUE TITLE
是否支持接入xinference部署的本地模型

### ISSUE THREAD

**Issue by linqingxu** [dataelement/bisheng#319]
尝试用customLLMChat接入xinference部署的chatglm2-6b模型，问答时出错，是否不支持xinference部署的本地模型？
![image](https://github.com/dataelement/bisheng/assets/146169982/7fecd0d5-8d7d-4165-8153-ef7dae215859)
问答：
![image](https://github.com/dataelement/bisheng/assets/146169982/b50435dd-d50e-45a4-b62b-d1450fe26ffc)
webUI问答：
![image](https://github.com/dataelement/bisheng/assets/146169982/dbbc3967-9099-42c1-a5bc-9059ee7761a4)

**Comment by yaojin3616** [comment]
如果是api调用，是都支持的。
目前看报错是Method Not Allowd， customLLM默认是用post传参的。可以先通过PostMan等工具测试api是否正常，然后再用CustomLLM

**Comment by Yiqian-Liu** [comment]
url应该是要加上v1/chat/completions之类的

**Comment by linqingxu** [comment]
已经解决了，xinference部署的模型服务如果走customLLMChat，会在validate_environment里加上infer，导致模型服务访问失败。新增xinference组件后实现对应功能。
![image](https://github.com/dataelement/bisheng/assets/146169982/fc4e397e-3b7e-4276-9bad-4438cb2afd6a)

**Comment by xs818818** [comment]
求教一下您是怎么改的，我也删除了infer貌似没用

**Comment by w62651515** [comment]
参考：https://dataelem.feishu.cn/wiki/NcOqw2QpzicHvqkmaUqcJjNpnEf 示例2

**Comment by w62651515** [comment]
> 参考：https://dataelem.feishu.cn/wiki/NcOqw2QpzicHvqkmaUqcJjNpnEf 示例2
