### ISSUE TITLE
Docker-Compose部署完成，后台服务始终502

### ISSUE THREAD

**Issue by eanfs** [dataelement/bisheng#336]
<img width="1477" alt="image" src="https://github.com/dataelement/bisheng/assets/5432110/6abf42dd-6549-4a65-bdd5-f6e0fe28fe99">

**Comment by yaojin3616** [comment]
需要看下您这边docker 的启动状态。
可能原因：
1. mysql的版本不是我们默认版本，启动异常： docker logs bisheng-mysql  可以看到启动相关日志
2. backend 启动异常，docker logs bisheng-backend 可以看到相关日志
