### ISSUE TITLE
openai proxy如何使用于embedding、chatGPT

### ISSUE THREAD

**Issue by huangbaichao** [dataelement/bisheng#35]
embedding知识或者与GPT对话时，如何填写配置reverse proxy地址使其可以正常访问？
postman测过端口可以，在知识库上传文件解析时一级chatGPT对话时，均失败。
proxy地址为：https://xxx/proxy/v1/chat/completions
代理服务器收到后会转成 https://api.openai.com/v1/chat/xxx

不管填写哪个地址都失败

<img width="1298" alt="image" src="https://github.com/dataelement/bisheng/assets/9191067/e78e6168-26f2-43f6-9940-f6a4af004bb6">
<img width="1641" alt="image" src="https://github.com/dataelement/bisheng/assets/9191067/d575d45e-96bf-4cbb-a64c-41ec82fd9b5a">
<img width="1599" alt="image" src="https://github.com/dataelement/bisheng/assets/9191067/33d1695f-ba21-4b77-b307-9968fee4d67d">

**Comment by yaojin3616** [comment]
1. 如果是单纯的proxy，将api_base_url 和 openai_proxy 填写对应的域名。 注意 base_url 应该填写到/v1 节点
2. 如果是通过proxy工具转换到域名。 将 api_base_url 填写 https://api.openai.com/v1/ 转换后到域名。节点会自动加上 v1/ 后面的路径
