### ISSUE TITLE
请问 AutoGenChain 这种组件目前支持流式么？

### ISSUE THREAD

**Issue by LZC6244** [dataelement/bisheng#422]
如官方文档示例中的【定义两个智能体，让他们打辩论】
![image](https://github.com/dataelement/bisheng/assets/29347833/ac7d58ae-7575-4133-9556-a8fb1207d631)
官方文档地址：https://dataelem.feishu.cn/wiki/CnwWw6BKti85zHkr3tgcUazlnVf

目前体验下来是 gpt 结果全部返回了才通过 ws 一次性全部 gpt 生成的内容/回答返回给前端

**Comment by yaojin3616** [comment]
真在优化中

**Comment by LZC6244** [comment]
那请问如何想本地部署改一下 AutoGenChain 为流式输出，大致要改哪些地方呢？方便的话可以简单说下不？

**Comment by yaojin3616** [comment]
已经支持
