### ISSUE TITLE
知识库embedding失败后，删除不掉文件

### ISSUE THREAD

**Issue by balancejia** [dataelement/bisheng#433]
![bisheng-error](https://github.com/dataelement/bisheng/assets/2674373/daeb88ae-4660-401a-8e3d-8ea370c69bc0)

**Comment by zzwtop1** [comment]
+1，我是更新了版本后才出现的这种情况，几个月前也出现过，当时我回退了版本，这次更新忘了备份版本了。。。

**Comment by zzwtop1** [comment]
> ![bisheng-error](https://private-user-images.githubusercontent.com/2674373/317160222-daeb88ae-4660-401a-8e3d-8ea370c69bc0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDI3NTksIm5iZiI6MTcxMTk0MjQ1OSwicGF0aCI6Ii8yNjc0MzczLzMxNzE2MDIyMi1kYWViODhhZS00NjYwLTQwMWEtOGUzZC04ZWEzNzBjNjliYzAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDMzNDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA3NTVjY2ZjNGU5Zjc2ZjYwZWQ5NzYwNzhhN2IwNDIwYWMzODY1NTYzZWMzNmQwYTUxYmMyZjYxNjc4YjM1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ib_h-YXd8lc3GTSWoLSspvcL02ASQ8SyiqbMOsG_Eqo)

今天有几个服务被我重启了，然后就能删除了，是不是跟服务启动项顺序有啥关系，搞不懂

**Comment by yaojin3616** [comment]
在2.3.2 版本是解决了。历史因为知识库没有生成数据，就去操作知识库，导致报错
