### ISSUE TITLE
本地部署后，没有图标【模型】

### ISSUE THREAD

**Issue by fanw52** [dataelement/bisheng#44]
使用最新的代码部署后，想通过应用本地部署的模型，发现找不到模型，如下图：
<img width="1449" alt="image" src="https://github.com/dataelement/bisheng/assets/26037497/6760e882-67dc-4100-a309-d305a080182d">

请问一下是哪里操作的有问题？

**Comment by huangbaichao** [comment]
mysql的modeldeploy表全部数据的status字段改成'未上线'试试看。

**Comment by YTed** [comment]
可能你需要把 mysql 里 user 表对应用户的 role 字段改为 admin

**Comment by yaojin3616** [comment]
最新版本，已经在部署文档里有更新如何配置admin账户
