### ISSUE TITLE
本地搭建的Milvus库，新建知识库，上传文档后卡死

### ISSUE THREAD

**Issue by studycode** [dataelement/bisheng#46]
本地搭建的Milvus库，上传完，一直是这个状态：
![c48cf6dc-b986-4ac9-aff8-9ae8fe0e3c8d](https://github.com/dataelement/bisheng/assets/1415034/4f0c1f17-12ea-4147-837a-25e5a02f341d)
后台：
<img width="590" alt="image" src="https://github.com/dataelement/bisheng/assets/1415034/a93951cf-eead-4907-a6d7-f6f2fff67fc0">
打开其他页面（后端卡死）：
<img width="1154" alt="image" src="https://github.com/dataelement/bisheng/assets/1415034/b771545c-cfc3-4dc3-a679-fde99b71d100">
本地Milvus日志：
<img width="1190" alt="image" src="https://github.com/dataelement/bisheng/assets/1415034/d2ba3850-876b-46ae-b907-175a5ad824cb">

**Comment by yaojin3616** [comment]
我们的启动参数 --workers 设置的多少？ 如果workers太少，又有同步处理场景，会导致处理进程被占用，无法相应其他请求。可以先考虑加大 --workers

**Comment by zhengxiang5965** [comment]
> 我们的启动参数 --workers 设置的多少？ 如果workers太少，又有同步处理场景，会导致处理进程被占用，无法相应其他请求。可以先考虑加大 --workers

docker-compose 启动的  在哪里设置 -- workers?

**Comment by yaojin3616** [comment]
可以通过docker-compose 的cmd。 目前在docker-compose.yml 文件下的backend节点上，已经示例了cmd配置

**Comment by hrfng** [comment]
已解决
