### ISSUE TITLE
配置本地向量化模型后，导入docx文档解析失败，txt没有问题，望解答

### ISSUE THREAD

**Issue by ZXP8080** [dataelement/bisheng#470]
![1](https://github.com/dataelement/bisheng/assets/42922767/0a6e8755-2419-4181-bc68-c1bb3687cc74)
![2](https://github.com/dataelement/bisheng/assets/42922767/2e7e89e5-0589-4239-a584-5a3ab9f13946)
![3](https://github.com/dataelement/bisheng/assets/42922767/b814d90f-a2c0-4dce-a617-27aed2cd69e8)

**Comment by ZXP8080** [comment]
![4](https://github.com/dataelement/bisheng/assets/42922767/dadea554-e4f8-47e6-b09a-2315746549c9)
![5](https://github.com/dataelement/bisheng/assets/42922767/7ca8cda4-c8fb-47ef-ba94-c65c5272f99c)
补充报错图片

**Comment by ZimaBlueee** [comment]
我也遇到了，请问是什么解决的呀
