### ISSUE TITLE
模型配置文件修改无法保存

### ISSUE THREAD

**Issue by lijieyuan** [dataelement/bisheng#474]
没有保存按钮呢？
![image](https://github.com/dataelement/bisheng/assets/23073445/61c4a1dc-4389-4ded-9403-97b923b44eb8)
![image](https://github.com/dataelement/bisheng/assets/23073445/c7b745a6-2010-499c-880e-f1b63b204828)

手动curl 接口也报错
![image](https://github.com/dataelement/bisheng/assets/23073445/4d3e3289-e5ba-49b8-875a-854510cc43eb)

谢谢解答

**Comment by yaojin3616** [comment]
界面的保存按钮需要下滑下弹窗。 覆盖了。
接口提示你 405 表示方法不被支持。可以看下是否model_def.json 传参是否有问题

**Comment by lijieyuan** [comment]
谢谢
