### ISSUE TITLE
【需求】添加组件时，部分组件的必要配置，能否在服务端配置默认值，并添加时默认使用这个默认值

### ISSUE THREAD

**Issue by huangbaichao** [dataelement/bisheng#49]
比如添加llm或者embedding相关组件时，能否后端服务启动时加载配置作为默认配置？
新增组件时就不用挨个配置这些了。
个别需要自定义的再自定义。
至少就我们目前使用的情况来看，每个都需要再配置挺麻烦的。

**Comment by yaojin3616** [comment]
是可以增加默认项的，目前大部分参数和个人账号信息相关，所以在代码中写默认值不是很合适。
我们可以考虑常用的配置，增加到配置文件里
