### ISSUE TITLE
[BUG][release分支]Milvus组件embedding无法使用

### ISSUE THREAD

**Issue by huangbaichao** [dataelement/bisheng#50]
文档问答、知识库问答场景，main分支配置的技能，前后端同步更新到release分支后，无法使用。
![image](https://github.com/dataelement/bisheng/assets/9191067/0526ee7a-f88b-4d75-bd6f-eaf3fe5b7957)

**Comment by dolphin0618** [comment]
接入知识库会自动采用知识库配置的 embedding

**Comment by huangbaichao** [comment]
> 接入知识库会自动采用知识库配置的 embedding

谢谢，已经可以使用了
