### ISSUE TITLE
本地部署时，python库 没有 bisheng_langchain 0.3.1

### ISSUE THREAD

**Issue by LZC6244** [dataelement/bisheng#504]
![image](https://github.com/dataelement/bisheng/assets/29347833/207a11b2-ca4a-407d-849f-2d0989c22501)
![image](https://github.com/dataelement/bisheng/assets/29347833/793daba0-c6a0-4db2-94d1-bdd80b0e7333)

**Comment by gitxulang** [comment]
俺也一眼

**Comment by LZC6244** [comment]
改为使用 `bisheng_langchain = "0.3.0rc1"` 可行
