### ISSUE TITLE
[咨询]: 前端工程为什么要在.gitignore中添加vite.config.ts

### ISSUE THREAD

**Issue by rico-zhang** [dataelement/bisheng#510]
1.前端工程为什么要在.gitignore中添加vite.config.ts？单纯的疑问。
2.前端工程是用vite创建的吧？但是看前端工程README是create-react-app？

**Comment by yaojin3616** [comment]
1. 有可能本地修改，不想同步到github，此方法是危险的，在后续中，改过来
2. 是react，

**Comment by dolphin0618** [comment]
0.3.3 开始隐藏私有配置，.gitignore恢复vite.config.ts
