### ISSUE TITLE
前端页面报错502

### ISSUE THREAD

**Issue by gexinworks** [dataelement/bisheng#566]
前端页面502，排查日志发现前端服务报错：

2024/05/19 11:23:15 [error] 39#39: *61 connect() failed (111: Connection refused) while connecting to upstream, client: ****, server: , request: "GET /api/v1/all HTTP/1.1", upstream: "http://172.18.0.2:7860/api/v1/all", host: "****:3001", referrer: "http://***3001/"
**** - - [19/May/2024:11:23:15 +0800] "GET /api/v1/all HTTP/1.1" 502 559 "http://***:3001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "-"

后端服务报错：

![image](https://github.com/dataelement/bisheng/assets/11661685/476acde4-396d-4fcc-8429-e82c0b4dabf0)

**Comment by gexinworks** [comment]
docker/bisheng/config/config.yaml 56行，由      filter: "lambda record: record['level'].name == 'INFO' and record['message'].startswith("k=s")"修改为      filter: "lambda record: record['level'].name == 'INFO' and record['message'].startswith('k=s')"

**Comment by alanyoungcy** [comment]
根本无法使用啊，密码登录什么都都进行不了

**Comment by guihaoqun** [comment]
2025年6月，都一年多了这个问题还是没解决？

<img width="1226" alt="Image" src="https://github.com/user-attachments/assets/1e23444e-218c-475c-9718-65292c9398a8" />
