### ISSUE TITLE
是否有计划放出bisheng-rt模块的源码？

### ISSUE THREAD

**Issue by Yanshang1991** [dataelement/bisheng#61]
目前没有bisheng-rt模块没有源码，只能拉镜像。请问是否有计划放出源码？

**Comment by yaojin3616** [comment]
当前项目已sub-module方式管理，可以直接连接到开源的bisheng-rt项目上

**Comment by hrfng** [comment]
@Yanshang1991  sub-module:  https://github.com/dataelement/bisheng-rt
