### ISSUE TITLE
私有化部署后web端无法登陆

### ISSUE THREAD

**Issue by XinGuo-Bill** [dataelement/bisheng#62]
web端登陆右下角显示下图，配置文件也已按照“私有化部署-配置文件介绍“更改，但仍无法登陆，请问该如何解决？
![3333333](https://github.com/dataelement/bisheng/assets/102718036/0be2b282-69a4-4b8e-b8a5-bc4af50a3099)

**Comment by dolphin0618** [comment]
重启一下后端镜像试试，该原因可能是过早的链接数据库失败导致；后续版本会处理

**Comment by XinGuo-Bill** [comment]
> 重启一下后端镜像试试，该原因可能是过早的链接数据库失败导致；后续版本会处理

重启试了一下，可以登陆，谢谢！
