### ISSUE TITLE
[Feature]模型上线支持.safetensors

### ISSUE THREAD

**Issue by Yiqian-Liu** [dataelement/bisheng#68]
（bisheng-rt好像没法提issue，借这里发一个）
模型上线功能支持.safetensors

**Comment by hrfng** [comment]
参考： https://dataelem.feishu.cn/wiki/KAl2wfI9nippfDktNKdclIIMnKf

部分模型已支持

**Comment by Yiqian-Liu** [comment]
按文档操作，.bin的模型上线没问题。上线QWEN-7B，模型文件是.safetensor，出现以下错误：
上线失败，Internal: OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./models/model_repository/qwen-7b-chat.

At:
  /usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py(2474): from_pretrained
  /usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py(488): from_pretrained
  /opt/bisheng-rt/./backends/python/pybackend_libs/dataelem/model/llm/llm.py(92): _load
  /opt/bisheng-rt/./backends/python/pybackend_libs/dataelem/model/llm/qwen.py(71): __init__
  /opt/bisheng-rt/./resource/internal_model_repository/graphs/huggingface_model/1/model.py(41): initialize

**Comment by Yiqian-Liu** [comment]
<html>
<body>
<div data-page-id="BYANdFBVXo7SFvxcYGHcyxkynxg" data-docx-has-block-data="true"><div>

use_safetensors | str, "1" or "0" , 1表示使用safetenosrs, 0表示不使用 llama2与qwen模型可使用safetensors格式 | “0”,  选填
-- | -- | --


</div></div><span data-lark-record-data="{&quot;isCut&quot;:false,&quot;rootId&quot;:&quot;BYANdFBVXo7SFvxcYGHcyxkynxg&quot;,&quot;parentId&quot;:&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;,&quot;blockIds&quot;:[46,47,48],&quot;recordIds&quot;:[&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;],&quot;recordMap&quot;:{&quot;ILNldHxjlo6DFHxodddcc8Fmndg&quot;:{&quot;id&quot;:&quot;ILNldHxjlo6DFHxodddcc8Fmndg&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;children&quot;:[&quot;Do2dduvwdo4LtjxsAVTc8u6CnFb&quot;]}},&quot;Do2dduvwdo4LtjxsAVTc8u6CnFb&quot;:{&quot;id&quot;:&quot;Do2dduvwdo4LtjxsAVTc8u6CnFb&quot;,&quot;snapshot&quot;:{&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;parent_id&quot;:&quot;ILNldHxjlo6DFHxodddcc8Fmndg&quot;,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7075171574977970179&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+f&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;use_safetensors&quot;}}}}},&quot;O5UTd5kYMoIkiIxWTymccH3KnVf&quot;:{&quot;id&quot;:&quot;O5UTd5kYMoIkiIxWTymccH3KnVf&quot;,&quot;snapshot&quot;:{&quot;children&quot;:[&quot;MXNodorN2o6YETxvQGSc3wSinlc&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7075171574977970179&quot;}},&quot;MXNodorN2o6YETxvQGSc3wSinlc&quot;:{&quot;id&quot;:&quot;MXNodorN2o6YETxvQGSc3wSinlc&quot;,&quot;snapshot&quot;:{&quot;hidden&quot;:false,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7075171574977970179&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;text&quot;:{&quot;0&quot;:&quot;str, \&quot;1\&quot; or \&quot;0\&quot; , 1表示使用safetenosrs, 0表示不使用\nllama2与qwen模型可使用safetensors格式&quot;},&quot;attribs&quot;:{&quot;0&quot;:&quot;*0|1+17*0+t&quot;}}},&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;text&quot;,&quot;comments&quot;:[],&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;children&quot;:[],&quot;folded&quot;:false,&quot;parent_id&quot;:&quot;O5UTd5kYMoIkiIxWTymccH3KnVf&quot;,&quot;locked&quot;:false}},&quot;LqHadp0mdo8zOyxCFnmcHqcOnEh&quot;:{&quot;id&quot;:&quot;LqHadp0mdo8zOyxCFnmcHqcOnEh&quot;,&quot;snapshot&quot;:{&quot;hidden&quot;:false,&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;children&quot;:[&quot;W5T0d31aXoL04excJFYcL38kn0m&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false}},&quot;W5T0d31aXoL04excJFYcL38kn0m&quot;:{&quot;id&quot;:&quot;W5T0d31aXoL04excJFYcL38kn0m&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;LqHadp0mdo8zOyxCFnmcHqcOnEh&quot;,&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7075171574977970179&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+8&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;“0”,  选填&quot;}}},&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;comments&quot;:[],&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;children&quot;:[]}},&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;:{&quot;id&quot;:&quot;ERqtdVFsKowcGexjSgCcbyrInVd&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;table&quot;,&quot;parent_id&quot;:&quot;BYANdFBVXo7SFvxcYGHcyxkynxg&quot;,&quot;comments&quot;:[],&quot;cell_set&quot;:{&quot;row1b583da5-7d75-4d0c-84b1-4c843d7213f9col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;PQMAdmAeyoBxyxx37txczNjmn5e&quot;},&quot;rowcec30b22-47db-4835-9908-2ef417889a62col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;D7BKdLuGIop8oHxPkQjcByDTnFh&quot;},&quot;rowcec30b22-47db-4835-9908-2ef417889a62coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;block_id&quot;:&quot;JjWpdXPy2oRer4xqKJycEydQnkc&quot;,&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1}},&quot;rowd9f7dbe7-dff5-48d9-9571-89560ed3177ecoldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;WYQCd4p5ho2K91x557gcMm7Jn5U&quot;},&quot;row306d3e07-4413-43c4-9b76-45f815159ec9col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;block_id&quot;:&quot;BGLrdYmfdobNJBxX6rvcDUK0nwc&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}},&quot;rowaa841594-20bd-4793-8bcb-61bf83b0e34acoldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;SPFSdOhkToU5ABxpMqKcaZSEnKg&quot;},&quot;rowadedca6d-08cb-4fb0-82e2-8b8efeb4cc47col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;RHwDdnOJtopiOKxCXEWcWnAdn3d&quot;},&quot;rowb2c591ab-c90f-476e-a033-2635a5a41aa3col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;KWb0dRvmUowAe3xC7eAcVIpgn6c&quot;},&quot;row1b583da5-7d75-4d0c-84b1-4c843d7213f9coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;VpmMd5mtpo4Wt2xjRUic730Gnkd&quot;},&quot;row306d3e07-4413-43c4-9b76-45f815159ec9col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;block_id&quot;:&quot;F4DadilFCo27dfxqCuDc5Jg4nsg&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}},&quot;row306d3e07-4413-43c4-9b76-45f815159ec9coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;OIZjdgmgkoYTtmxlsumcXmt2nXe&quot;},&quot;row9dfcb376-3bba-4fed-9959-0f353de3d7d8col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;PnJ9d8uDQo4q9Rx8u7QczIQxnjg&quot;},&quot;row8415a1cf-b9d7-45a1-a295-28e230b4cb4bcoldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;O5UTd5kYMoIkiIxWTymccH3KnVf&quot;},&quot;rowaa841594-20bd-4793-8bcb-61bf83b0e34acol92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;block_id&quot;:&quot;ItX0dwbT4ofdxpxvkHRcOaIAnhh&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}},&quot;rowb2c591ab-c90f-476e-a033-2635a5a41aa3col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;UTOKdidXCoOht7xP1mVcxTzmn9f&quot;},&quot;rowb2c591ab-c90f-476e-a033-2635a5a41aa3coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;block_id&quot;:&quot;GoyCdDU0Co6xivx1zSDcbvvKngd&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}},&quot;row9dfcb376-3bba-4fed-9959-0f353de3d7d8col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;YSDtdbg2nokBcnx8cb2ccfe2nne&quot;},&quot;rowaa841594-20bd-4793-8bcb-61bf83b0e34acol147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;SdpBdb9GaoNuPVxKI9BcZUoQnVd&quot;},&quot;rowadedca6d-08cb-4fb0-82e2-8b8efeb4cc47coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;INIyd3utAoKcexxdgpPcL4ZXnXe&quot;},&quot;rowd9f7dbe7-dff5-48d9-9571-89560ed3177ecol92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;block_id&quot;:&quot;XemedG6cIoYSiAxx7NpctvLhnUY&quot;,&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1}},&quot;rowcec30b22-47db-4835-9908-2ef417889a62col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;GjZvdpjpSoP9IdxjUR3cAaSPn0f&quot;},&quot;row1b583da5-7d75-4d0c-84b1-4c843d7213f9col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;NVbndG5O6oXXejxszXfc9522ntb&quot;},&quot;row8415a1cf-b9d7-45a1-a295-28e230b4cb4bcol147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;LqHadp0mdo8zOyxCFnmcHqcOnEh&quot;},&quot;row8415a1cf-b9d7-45a1-a295-28e230b4cb4bcol92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;ILNldHxjlo6DFHxodddcc8Fmndg&quot;},&quot;row9dfcb376-3bba-4fed-9959-0f353de3d7d8coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;DXAgdV6zIoOJE6xahEqcDuRxnff&quot;},&quot;rowadedca6d-08cb-4fb0-82e2-8b8efeb4cc47col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;ORdKdh5uvobLSLx6VJdcB1zdnZc&quot;},&quot;rowd9f7dbe7-dff5-48d9-9571-89560ed3177ecol147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;block_id&quot;:&quot;OqbIdlXYHoDWAGxKrqWch4zFnxe&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}}},&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7075171574977970179&quot;,&quot;columns_id&quot;:[&quot;col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;,&quot;coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;,&quot;col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;],&quot;rows_id&quot;:[&quot;row8415a1cf-b9d7-45a1-a295-28e230b4cb4b&quot;],&quot;column_set&quot;:{&quot;col92eca556-0e06-4443-a6e2-ef7b11f9697f&quot;:{&quot;column_width&quot;:156},&quot;coldf8d0842-2282-4ac4-8ecb-368baf6dbe89&quot;:{&quot;column_width&quot;:414},&quot;col147f11c3-15da-4d0d-a3dc-aaef5acc4e04&quot;:{&quot;column_width&quot;:141}}}}},&quot;payloadMap&quot;:{&quot;Do2dduvwdo4LtjxsAVTc8u6CnFb&quot;:{&quot;level&quot;:1},&quot;MXNodorN2o6YETxvQGSc3wSinlc&quot;:{&quot;level&quot;:1},&quot;W5T0d31aXoL04excJFYcL38kn0m&quot;:{&quot;level&quot;:1}},&quot;extra&quot;:{&quot;mention_page_title&quot;:{},&quot;external_mention_url&quot;:{}},&quot;isKeepQuoteContainer&quot;:false,&quot;selection&quot;:[{&quot;id&quot;:46,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;ILNldHxjlo6DFHxodddcc8Fmndg&quot;},{&quot;id&quot;:47,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;O5UTd5kYMoIkiIxWTymccH3KnVf&quot;},{&quot;id&quot;:48,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;LqHadp0mdo8zOyxCFnmcHqcOnEh&quot;}],&quot;pasteFlag&quot;:&quot;af2eebbb-6064-4e4f-96e7-f22070d614d1&quot;}" data-lark-record-format="docx/record" class="lark-record-clipboard"></span>
</body>
</html>
