### ISSUE TITLE
bisheng-rt支持vllm

### ISSUE THREAD

**Issue by PatrickStar-SJ** [dataelement/bisheng#70]

**Comment by hrfng** [comment]
## 速度

|  模型     |  vLLM  | hf+accelate | 
| --- | --- |  --- |
|   qwen-14b            |           |              |
|   qwen-7b              |           |              |
|   baichuan2-13b    |           |              |
|   iternlm-20b          |           |              |

## 显存占用

|  模型     |  vLLM  | hf+accelate | 
| --- | --- |  --- |
|   qwen-14b            |           |              |
|   qwen-7b              |           |              |
|   baichuan2-13b    |           |              |
|   iternlm-20b          |           |              |
