### ISSUE TITLE
[BUG]RetrivalQA勾选return source documents后API调用错误

### ISSUE THREAD

**Issue by Yiqian-Liu** [dataelement/bisheng#71]
RetrivalQA勾选return source documents后API调用错误：{'detail': "Error: `run` not supported when there is not exactly one output key. Got ['result', 'source_documents']."}
![微信截图_20231010164146](https://github.com/dataelement/bisheng/assets/39006687/07d4229f-b3f5-4778-8095-c9e48c01f4d5)
![微信截图_20231010164211](https://github.com/dataelement/bisheng/assets/39006687/6b9f7da4-1253-4e1c-9b05-bb0489d96fd4)

**Comment by yaojin3616** [comment]
看您使用的LLM是chatWenxin，这个组件目前需要进入他的高级配置，配置下max_token。 
您可以关注到backend日志，提示
`bisheng_langchain.chat_models.wenxin.Chat
                    Wenxin.completion_with_retry.<locals>._co
                    mpletion_with_retry in 8.0 seconds as it
                    raised ValidationError: 1 validation
                    error for ChatInput
                    max_tokens
                      none is not an allowed value
                    (type=type_error.none.not_allowed).`
                    
我这边测试，是可以返回source，执行过程我们继续优化提示
