### ISSUE TITLE
 docker-compose up -d启动项目服务时，报错：ERROR: The Compose file './docker-compose.yml' is invalid because: services.office.environment.JWT_ENABLED contains false, which is an invalid type, it should be a string, number, or a null

### ISSUE THREAD

**Issue by jiangzongjie** [dataelement/bisheng#718]
1、问题现象：在ubuntu下执行docker-compose up -d启动项目服务时，报错：ERROR: The Compose file './docker-compose.yml' is invalid because: services.office.environment.JWT_ENABLED contains false, which is an invalid type, it should be a string, number, or a null

2、问题排查：docker-compose.yml 文件中，在 services.office.environment.JWT_ENABLED 这个字段处有一个值设置错误。Docker Compose 的环境变量（environment）字段中的值应该是一个字符串、数字或者 null。而原项目似乎被设置为了布尔值 false

3、问题修复：将 JWT_ENABLED 的值从 false 改为一个字符串 "false"，修改项目的 docker-compose.yml 文件中的相应部分，如下所示：
![image](https://github.com/dataelement/bisheng/assets/173236065/56302243-78fc-495b-865c-49b436291967)
![Uploading yml文件修改.jpg…]()

**Comment by yaojin3616** [comment]
收到

**Comment by cumtsd** [comment]
谢谢 有用

**Comment by ieayoio** [comment]
不过如果使用`docker compose up -d`（docker与compose有空格）命令运行，这个问题就不存在了
