### ISSUE TITLE
知识库连接ElasticKeywordsSearch异常

### ISSUE THREAD

**Issue by shishugen** [dataelement/bisheng#744]
知识库连接ElasticKeywordsSearch异常，不知道怎么配置这个
不要验证就报这个错误
![image](https://github.com/user-attachments/assets/57c5da21-efeb-42a4-a8e3-6a4263d8bf3f)
![image](https://github.com/user-attachments/assets/4ed6c81d-19ea-41da-8c81-653e916f01d3)
我启动配置验证就报这个错误，我在bisheng-backend这个容器中测试登录是没有问题的
![image](https://github.com/user-attachments/assets/f45b2f00-efd5-4b06-a25e-5cdcaf21867e)
![image](https://github.com/user-attachments/assets/f97b74ef-0356-4b75-acb4-e0ecd15b8b6b)
![image](https://github.com/user-attachments/assets/cca8aadd-a69d-4ecc-a39f-e4cdadf01649)

**Comment by yaojin3616** [comment]
从报错看，就是网络连接不通

**Comment by shishugen** [comment]
> 从报错看，就是山顶不通。

**Comment by shishugen** [comment]
> 从报错看，就是山顶不通。

![image](https://github.com/user-attachments/assets/abd70e12-b18b-4037-8ae8-2695871ac3a9)
我进入容器是可以通的

**Comment by buzaizai** [comment]
同样报错

**Comment by buzaizai** [comment]
ping ，直接访问能访问通

**Comment by buzaizai** [comment]
已解决，es磁盘空间满的保护机制，更换挂载点解决
