### ISSUE TITLE
使用镜像运行时，提示AttributeError: 'Minio' object has no attribute '_http'

### ISSUE THREAD

**Issue by luocj** [dataelement/bisheng#90]
运行环境：linux centos安装docker环境下运行
版本：docker-compose的版本为3.4，运行时backend模块报错
![image](https://github.com/dataelement/bisheng/assets/6811743/43b49c90-9d83-46d2-92fc-a8891ceb7243)
  
通过查询minio的版本为7.1.17 调整版本到7.1.1后仍然报错，请问那个版本为正确的版本

**Comment by rainySummers** [comment]
用docker启动一个minio，把配置文件里面的minio改上正确的地址和凭据就ok了

**Comment by luocj** [comment]
> 用docker启动一个minio，把配置文件里面的minio改上正确的地址和凭据就ok了

感谢提醒，启动并配置minio后依然报同样的错误，请问是我哪里没有配置对吗？
容器启动情况：
![image](https://github.com/dataelement/bisheng/assets/6811743/a1a20ba2-1401-4706-bc26-c42bbfb19b28)
配置文件情况：
![image](https://github.com/dataelement/bisheng/assets/6811743/11d8d150-b62a-4e2e-a01c-e881a53b3c7f)
在backend的容器中telnet 测试minio的端口情况：
![image](https://github.com/dataelement/bisheng/assets/6811743/d24ad4b1-35a3-47e0-ba29-0e789843a5f0)
backend启动报错：
![image](https://github.com/dataelement/bisheng/assets/6811743/0b237d47-22a9-469d-b427-c6b7ba336ea1)
